version0chiro/Find-Me-Issues

client/package.json
client/src/components/SingleCard.js

Used emoji-js library to fix emoji issue

Fix Issue #7

---

client/package.json
client/src/components/SingleCard.js

Reverts version0chiro/Find-Me-Issues#9

Revert "Fix Issue #7"

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/CardSet.js
client/src/components/Header.js
client/src/components/IssuesList.js
client/src/components/SingleCard.js

Fixed the problem of emojis not rendering with the help of react-emoji-render npm package.

fixed emoji rendering

---

client/package-lock.json
client/src/components/Navigation.js
client/yarn.lock
package-lock.json

Made improvements to the UI for the page div and also added some active state functionality. 
Fixes issue #4. 
- Used React Bootstrap Pagination Component
- Used Material UI Hooks API to apply custom styles
- Applied a brute force solution to apply active states to the current page
The active states functionality is brute force and could use some refactoring if possible. Please let me know if there is anything else I can improve on. Thanks!

Improvements to the page changing div. Fixes issue #4. 

---

client/src/components/Navigation.js

Add functionality to change pages when user clicks on the page number. 
Improves user experience when navigating the website. 
Added an ```onClick()``` event to the ```<Pagination.Item>``` component. The event handler sets the state of ```pageNumber``` to the page number that is clicked on. 
```js
<Pagination.Item
onClick={() => {
props.setPageNumber(pageNumber);
}}
>
{pageNumber}
</Pagination.Item>,
```

Make improvements to page changing div

---

client/src/components/CardSet.js
client/src/index.css

Greetings ✌
Attempting to close #18
- Added simple css loading animation that is rendered while the issues are being fetched from the github api.
css for the loading animation is from the w3scools examples (I'm not really good at the design part, sorry)

Added simple css animation while fetching issue list.

---

client/package.json
client/src/components/CardSet.js
client/src/components/Header.js
client/src/components/SingleCard.js
client/yarn.lock

There are two scenarios where the rate limits occurs:
1- When requesting the issue list
2- When requesting individual repos
In consequence the requests do not return the proper data resulting on the type error. 
- When a status 403 is sent from the github api, a message shows up, alerting the user about rate limiting and to wait/refresh while the server can again fulfill requests. 
This prevents the page from crashing and serves as a workaround while the problem is handled/addressed in a better way.
I've added two additional packages to facilitate this implementation:
- lodash (utils)
- axios (for requests)
This can possibly be solved using a github account (has better rate limits) and making the api calls from the express server for security reasons, mainly to not expose the github …

TypeError fix. handling github api ratelimit. 

---

client/public/index.html
client/src/App.js
client/src/Context/themeContext.js
client/src/components/CardSet.js
client/src/components/Header.js
client/src/components/Navigation.js
client/src/components/SingleCard.js
client/src/index.css
client/src/index.js

Closes #20 
- Used react context to provide a global state for the theme variable object.
- User system theme preference is detected and set.
- Created a button for changing theme.   
####Preview:

Added toggle between ligh and dark themes functionality. closes #20

---

.gitignore

added /node_modules to the .gitignore file

added /node_modules to the .gitignore file

---

client/src/App.js
client/src/components/CardSet.js
client/src/components/Header.js
client/src/components/SingleCard.js

1. Changed the URL to fetch repositories with labels "good first issue" and added sort parameters according to the github api docs.
2. Added 'sort by stars' and 'sort by forks' button in the header to change the URL accordingly.
3. By default all the repositories are fetched in descending order of their "stars".
4. Changed the "Get Issues" link to point to the repository's issues section.

Sorting repos on the basis of stars and forks

---

README.md

1) Fixed typo on the README file

fix: readme file has a small typo

---

client/src/App.js
client/src/components/CardSet.js
client/src/components/RepoFilters.js
package.json

New Filter options to be added to the search 
Added filter options for minimum and maximum forks and stars
Fixes #17 
- BEFORE
- AFTER

Added new filter options - forks and stars count

---

README.md

Reverts version0chiro/Find-Me-Issues#43

Revert "README file updated"

---

client/src/data/languages.json

As requested in the Issue #3 I've added new languages to the available selectable languages in the interface dropdown.

chore: add more searcheable languages

---

README.md

This pull request enhances the project's README documentation by adding several important sections for improved clarity and user-friendliness.
- Added a "Table of Contents" section for quick navigation through the documentation.
- Added a "How To" section, providing clear instructions on installation and usage of the project.
- Introduced a "Description" section for a concise overview of the project.
- Included a "Table of Contents" to aid in navigation within the README.
- Added a "Features" section to highlight the key functionalities of the project.
- Included a "License" section to clarify the licensing terms of the project.
The purpose of these changes is to make it easier for users, both new and experienced, to understand and utilize our project effectively. The "How To" section …

(2023-10-01) Documentation Update; Changed README.md (Informational and Structural Update)

---

src/data/languages.json

As the requested issue #3, I added multiple searchable languages.

add more searchable languages

---

src/data/languages.json

In this PR, add the following languages:
#3

Add fortran language

---

src/components/CardSet.js

Refactor CardSet component to use destructured props to prevent re-rendering

fix: Issue-99

---

src/components/Header.css
src/components/Header.js

Description:
This pull request resolves issue https://github.com/version0chiro/Find-Me-Issues/issues/103, where clicking on "JavaScript" in the menu would expand all technologies in the menu and cause the entire site to scroll when attempting to scroll within the menu.
Changes Made:
Fixed the height of dropdown menu and made that dropdown scrollable.

fix: issue 103

---

src/components/Header.js

Description: 
This pull request resolves issue #113, where the selected language repeats itself in the dropdown menu.
Changes made: 
I've added a filter to the dropdown menu so that the selected "language" does not repeat itself again in the dropdown.

Tackling issue #113

---

src/data/languages.json

In this PR, add the following languages:

Add new programming langauges

---

src/data/languages.json

Hey @version0chiro ,
I have started my Hacktoberfest journey by contributing a language (Smalltalk) in language.json .
Kindly consider my PR.
Thanks and regards,
Heeba

Fixed issue no. #3 : Add more languages to languages.json

---

src/components/Buttons/Darkmode.js
src/components/Buttons/Language.js
src/components/Header.js
src/components/Navigation.js

Issue Link : [#130](https://github.com/version0chiro/Find-Me-Issues/issues/130).
-Used custom select component for better ui
-Used tailwindCSS to make the things responsiveness
-Used some ui concepts for bring a better searchBar

isuue #130: Fixed Select/Languages Aspects - Responsiveness Nav bar - Better  SearchBar

---

src/Context/themeContext.js

Fixed issue #120 
This commit refactors theme context for better readability and performance by centralizing theme retrieval, updating localStorage, and memoizing context to reduce re-renders.

Fixed issue no #120 : added persistent theme on refresh
